"""Bekannte Escape Rooms in Berlin — Datenbasis für initiale Befüllung.

Diese Daten werden beim Scraping als Fallback verwendet, wenn die Website
nicht erreichbar ist oder sich die Struktur geändert hat.
"""

KNOWN_ROOMS = [
    # === EXITROOM (10 Räume, Mitte) ===
    {"name": "Maniac", "provider": "EXITROOM", "district": "Mitte", "theme": "Horror",
     "players": "3-6", "duration": 60, "difficulty": "Mittel", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Sherlock", "provider": "EXITROOM", "district": "Mitte", "theme": "Krimi",
     "players": "2-6", "duration": 60, "difficulty": "Mittel", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Zombie", "provider": "EXITROOM", "district": "Mitte", "theme": "Horror",
     "players": "3-6", "duration": 60, "difficulty": "Schwer", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Zauberschule", "provider": "EXITROOM", "district": "Mitte", "theme": "Fantasy",
     "players": "3-6", "duration": 60, "difficulty": "Mittel", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Bankjob", "provider": "EXITROOM", "district": "Mitte", "theme": "Krimi",
     "players": "2-6", "duration": 60, "difficulty": "Schwer", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Halblinge", "provider": "EXITROOM", "district": "Mitte", "theme": "Fantasy",
     "players": "2-6", "duration": 60, "difficulty": "Leicht", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Da Vinci", "provider": "EXITROOM", "district": "Mitte", "theme": "Historie",
     "players": "3-6", "duration": 60, "difficulty": "Schwer", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Wunderlampe", "provider": "EXITROOM", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "Mittel", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Piraten Schatz", "provider": "EXITROOM", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "Mittel", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "Wilhelmstraße 92, 10117 Berlin", "active": True},
    {"name": "Führer Bunker", "provider": "EXITROOM", "district": "Mitte", "theme": "Historie",
     "players": "3-6", "duration": 60, "difficulty": "Schwer", "price_from": 35.0,
     "booking_url": "https://exitroom.berlin/buchen-escape-room-berlin",
     "room_url": "https://www.exitroom.berlin/escape-rooms-berlin",
     "address": "An der Kolonnade 4, 10117 Berlin", "active": True},

    # === EXIT Game (6 Räume, Mitte) ===
    {"name": "Magic Alley", "provider": "EXIT Game", "district": "Mitte", "theme": "Fantasy",
     "players": "4-8", "duration": 66, "difficulty": "", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/magic-alley",
     "room_url": "https://www.exit-game.de/game/magic-alley",
     "address": "Berlin Mitte", "active": True},
    {"name": "Prison Island Battle Modus", "provider": "EXIT Game", "district": "Mitte", "theme": "Action",
     "players": "8-14", "duration": 66, "difficulty": "", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/prison-island-battle-modus",
     "room_url": "https://www.exit-game.de/game/prison-island-battle-modus",
     "address": "Berlin Mitte", "active": True},
    {"name": "Prison Island", "provider": "EXIT Game", "district": "Mitte", "theme": "Action",
     "players": "3-7", "duration": 66, "difficulty": "", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/prison-island",
     "room_url": "https://www.exit-game.de/game/prison-island",
     "address": "Berlin Mitte", "active": True},
    {"name": "Monster Party", "provider": "EXIT Game", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-10", "duration": 66, "difficulty": "Leicht", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/monster-party",
     "room_url": "https://www.exit-game.de/game/monster-party",
     "address": "Berlin Mitte", "active": True},
    {"name": "Admiral Kingdom", "provider": "EXIT Game", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 66, "difficulty": "", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/admiral-kingdom",
     "room_url": "https://www.exit-game.de/game/admiral-kingdom",
     "address": "Berlin Mitte", "active": True},
    {"name": "Flucht und Spionage an der Berliner Mauer", "provider": "EXIT Game", "district": "Mitte",
     "theme": "Historie", "players": "2-6", "duration": 120, "difficulty": "", "price_from": None,
     "booking_url": "https://www.exit-game.de/game/teamrallye",
     "room_url": "https://www.exit-game.de/game/teamrallye",
     "address": "Berlin Mitte", "active": True},

    # === Escape Berlin (13 Räume, Lichtenberg) ===
    {"name": "Sherlocks Falle", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Krimi",
     "players": "2-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/18-sherlocksaefalle/",
     "room_url": "https://www.escape-berlin.de/de/live/18-sherlocksaefalle/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Sherlock Holmes", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Krimi",
     "players": "2-8", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/1-sherlockaeholmes/",
     "room_url": "https://www.escape-berlin.de/de/live/1-sherlockaeholmes/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Knast", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Thriller",
     "players": "3-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/23-knast/",
     "room_url": "https://www.escape-berlin.de/de/live/23-knast/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Superzwerg", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Abenteuer",
     "players": "2-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/10-superzwerg/",
     "room_url": "https://www.escape-berlin.de/de/live/10-superzwerg/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Sherlocks Traum", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Krimi",
     "players": "2-8", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/11-sherlocksaetraum/",
     "room_url": "https://www.escape-berlin.de/de/live/11-sherlocksaetraum/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Schnapsladen", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Comedy",
     "players": "2-9", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/5-schnapsladen/",
     "room_url": "https://www.escape-berlin.de/de/live/5-schnapsladen/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Puppenspieler", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Horror",
     "players": "2-4", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/14-puppenspieler/",
     "room_url": "https://www.escape-berlin.de/de/live/14-puppenspieler/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Partykeller", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Comedy",
     "players": "2-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/13-partykeller/",
     "room_url": "https://www.escape-berlin.de/de/live/13-partykeller/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Hitzefrei", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Abenteuer",
     "players": "4-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/22-hitzefrei/",
     "room_url": "https://www.escape-berlin.de/de/live/22-hitzefrei/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Sturmfrei", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Abenteuer",
     "players": "2-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/15-sturmfrei/",
     "room_url": "https://www.escape-berlin.de/de/live/15-sturmfrei/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Mutprobe", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Horror",
     "players": "3-8", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/19-mutprobe/",
     "room_url": "https://www.escape-berlin.de/de/live/19-mutprobe/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Happy Hour", "provider": "Escape Berlin", "district": "Lichtenberg", "theme": "Comedy",
     "players": "4-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.escape-berlin.de/de/live/21-happyaehour/",
     "room_url": "https://www.escape-berlin.de/de/live/21-happyaehour/",
     "address": "Berlin Lichtenberg", "active": True},

    # === Black Room (10 Räume, Lichtenberg) ===
    {"name": "QUIZY Game Show", "provider": "Black Room", "district": "Lichtenberg", "theme": "Comedy",
     "players": "2-18", "duration": 60, "difficulty": "Mittel", "price_from": 22.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/quiz/",
     "room_url": "https://berlin.blackroom-escape.de/product/quiz/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Harry's letzte Verteidigung", "provider": "Black Room", "district": "Lichtenberg", "theme": "Fantasy",
     "players": "2-7", "duration": 60, "difficulty": "Schwer", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/harrys-letzte-verteidigung/",
     "room_url": "https://berlin.blackroom-escape.de/product/harrys-letzte-verteidigung/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Stranger Escape", "provider": "Black Room", "district": "Lichtenberg", "theme": "Sci-Fi",
     "players": "2-7", "duration": 60, "difficulty": "Schwer", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/stranger-escape/",
     "room_url": "https://berlin.blackroom-escape.de/product/stranger-escape/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Escape of Thrones", "provider": "Black Room", "district": "Lichtenberg", "theme": "Fantasy",
     "players": "2-7", "duration": 60, "difficulty": "Schwer", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/escape-of-thrones/",
     "room_url": "https://berlin.blackroom-escape.de/product/escape-of-thrones/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Kinder im All-Alarm", "provider": "Black Room", "district": "Lichtenberg", "theme": "Sci-Fi",
     "players": "2-7", "duration": 60, "difficulty": "Leicht", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/kinder-im-all-alarm/",
     "room_url": "https://berlin.blackroom-escape.de/product/kinder-im-all-alarm/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Harrys Zauberschule", "provider": "Black Room", "district": "Lichtenberg", "theme": "Fantasy",
     "players": "2-7", "duration": 60, "difficulty": "Mittel", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/harrys-zauberschule/",
     "room_url": "https://berlin.blackroom-escape.de/product/harrys-zauberschule/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Resident Virus", "provider": "Black Room", "district": "Lichtenberg", "theme": "Horror",
     "players": "2-7", "duration": 60, "difficulty": "Mittel", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/resident-virus/",
     "room_url": "https://berlin.blackroom-escape.de/product/resident-virus/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Annabelles Horror", "provider": "Black Room", "district": "Lichtenberg", "theme": "Horror",
     "players": "2-7", "duration": 60, "difficulty": "Mittel", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/annabelles-horror/",
     "room_url": "https://berlin.blackroom-escape.de/product/annabelles-horror/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Das Verbotene Rezept", "provider": "Black Room", "district": "Lichtenberg", "theme": "Mystery",
     "players": "2-7", "duration": 60, "difficulty": "Mittel", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/das-verbotene-rezept/",
     "room_url": "https://berlin.blackroom-escape.de/product/das-verbotene-rezept/",
     "address": "Berlin Lichtenberg", "active": True},
    {"name": "Wednesday und der Fluch der Addams", "provider": "Black Room", "district": "Lichtenberg",
     "theme": "Horror", "players": "2-7", "duration": 60, "difficulty": "Mittel", "price_from": 19.0,
     "booking_url": "https://berlin.blackroom-escape.de/product/wednesday-und-der-fluch-der-addams/",
     "room_url": "https://berlin.blackroom-escape.de/product/wednesday-und-der-fluch-der-addams/",
     "address": "Berlin Lichtenberg", "active": True},

    # === TeamEscape (6 Räume, Charlottenburg) ===
    {"name": "Anne Bonnys Schatz", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/anne-bonnys-schatz/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/anne-bonnys-schatz/",
     "address": "Berlin Charlottenburg", "active": True},
    {"name": "Blood Lust", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Horror",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/blood-lust/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/blood-lust/",
     "address": "Berlin Charlottenburg", "active": True},
    {"name": "Rabbit6", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Mystery",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/rabbit6/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/rabbit6/",
     "address": "Berlin Charlottenburg", "active": True},
    {"name": "Revolución Olé", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/revolucion-ole/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/revolucion-ole/",
     "address": "Berlin Charlottenburg", "active": True},
    {"name": "Secret Service", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Thriller",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/secret-service/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/secret-service/",
     "address": "Berlin Charlottenburg", "active": True},
    {"name": "Space Escape", "provider": "TeamEscape", "district": "Charlottenburg", "theme": "Sci-Fi",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 31.0,
     "booking_url": "https://teamescape.com/berlin/escape-rooms/space-escape/",
     "room_url": "https://teamescape.com/berlin/escape-rooms/space-escape/",
     "address": "Berlin Charlottenburg", "active": True},

    # === House of Tales (6 Räume, Mitte) ===
    {"name": "One Night in Hong Kong", "provider": "House of Tales", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},
    {"name": "Der Fluch des Pharaos", "provider": "House of Tales", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},
    {"name": "Checkpoint Charlie", "provider": "House of Tales", "district": "Mitte", "theme": "Historie",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},
    {"name": "Die Illuminati Obsession", "provider": "House of Tales", "district": "Mitte", "theme": "Thriller",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},
    {"name": "Der Henker", "provider": "House of Tales", "district": "Mitte", "theme": "Horror",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},
    {"name": "Versus Game", "provider": "House of Tales", "district": "Mitte", "theme": "Action",
     "players": "4-12", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.houseoftales.de/tickets",
     "room_url": "https://www.houseoftales.de",
     "address": "Zimmerstraße 90, 10117 Berlin", "active": True},

    # === Labyrintoom (4 Räume, Lichtenberg) ===
    {"name": "Leonardo da Vinci's Cabinet", "provider": "Labyrintoom", "district": "Lichtenberg", "theme": "Historie",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://labyrintoom.com/book-now",
     "room_url": "https://labyrintoom.com",
     "address": "Wartenberg Str. 35/36, 10365 Berlin", "active": True},
    {"name": "The Wizard's Cabinet", "provider": "Labyrintoom", "district": "Lichtenberg", "theme": "Fantasy",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://labyrintoom.com/book-now",
     "room_url": "https://labyrintoom.com",
     "address": "Wartenberg Str. 35/36, 10365 Berlin", "active": True},
    {"name": "The Cube's Cabinet", "provider": "Labyrintoom", "district": "Lichtenberg", "theme": "Sci-Fi",
     "players": "2-6", "duration": 60, "difficulty": "Schwer", "price_from": None,
     "booking_url": "https://labyrintoom.com/book-now",
     "room_url": "https://labyrintoom.com",
     "address": "Wartenberg Str. 35/36, 10365 Berlin", "active": True},
    {"name": "Mind Arena", "provider": "Labyrintoom", "district": "Lichtenberg", "theme": "Mystery",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://labyrintoom.com/book-now",
     "room_url": "https://labyrintoom.com",
     "address": "Wartenberg Str. 35/36, 10365 Berlin", "active": True},

    # === Illuminati Escape (5 Indoor + 4 Outdoor, Charlottenburg) ===
    {"name": "Alien Grill", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Sci-Fi",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 25.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen.html#aliengrill",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Cyber Attack", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Sci-Fi",
     "players": "2-5", "duration": 60, "difficulty": "", "price_from": 25.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen.html#cyberattack",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Jackpot", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Krimi",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": 25.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen.html#jackpot",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Titanik 2.0", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Abenteuer",
     "players": "5-9", "duration": 60, "difficulty": "", "price_from": 25.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen.html#titanik",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Cyber Attack Teams", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Sci-Fi",
     "players": "4-10", "duration": 60, "difficulty": "", "price_from": 25.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen.html#cyberattackteam",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Safe House (Outdoor)", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Thriller",
     "players": "2-8", "duration": 120, "difficulty": "", "price_from": 80.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen-outdoor.html#safehouse",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},
    {"name": "Skywatch (Outdoor)", "provider": "Illuminati Escape", "district": "Charlottenburg", "theme": "Sci-Fi",
     "players": "2-8", "duration": 120, "difficulty": "", "price_from": 80.0,
     "booking_url": "https://www.illuminati-escape.com/escaperoom/berlin/de/buchen-outdoor.html#skywatch",
     "room_url": "https://www.illuminati-escape.com",
     "address": "Abbestraße 17, 10587 Berlin", "active": True},

    # === Cat in the Bag (3 Räume, Mitte) ===
    {"name": "Gefängnis", "provider": "Cat in the Bag", "district": "Mitte", "theme": "Thriller",
     "players": "2-6", "duration": 60, "difficulty": "Leicht", "price_from": None,
     "booking_url": "https://www.catinthebag.de/booking",
     "room_url": "https://www.catinthebag.de",
     "address": "Chausseestraße 15, 10115 Berlin", "active": True},
    {"name": "Bunker", "provider": "Cat in the Bag", "district": "Mitte", "theme": "Horror",
     "players": "2-6", "duration": 60, "difficulty": "Schwer", "price_from": None,
     "booking_url": "https://www.catinthebag.de/booking",
     "room_url": "https://www.catinthebag.de",
     "address": "Chausseestraße 15, 10115 Berlin", "active": True},
    {"name": "Skihütte", "provider": "Cat in the Bag", "district": "Mitte", "theme": "Abenteuer",
     "players": "2-6", "duration": 60, "difficulty": "Mittel", "price_from": None,
     "booking_url": "https://www.catinthebag.de/booking",
     "room_url": "https://www.catinthebag.de",
     "address": "Chausseestraße 15, 10115 Berlin", "active": True},

    # === MIRACULUM (3 Räume, Kreuzberg) ===
    {"name": "MIRACULUM Room 1", "provider": "MIRACULUM", "district": "Kreuzberg", "theme": "Mystery",
     "players": "2-5", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.miraculum-escape.de",
     "room_url": "https://www.miraculum-escape.de",
     "address": "Stresemannstr. 50, 10963 Berlin", "active": True},
    {"name": "MIRACULUM Room 2", "provider": "MIRACULUM", "district": "Kreuzberg", "theme": "Mystery",
     "players": "2-5", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.miraculum-escape.de",
     "room_url": "https://www.miraculum-escape.de",
     "address": "Stresemannstr. 50, 10963 Berlin", "active": True},
    {"name": "MIRACULUM Room 3", "provider": "MIRACULUM", "district": "Kreuzberg", "theme": "Mystery",
     "players": "2-5", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://www.miraculum-escape.de",
     "room_url": "https://www.miraculum-escape.de",
     "address": "Stresemannstr. 50, 10963 Berlin", "active": True},

    # === your time2escape (2 Räume, Wedding) ===
    {"name": "Doktor Kannibal", "provider": "your time2escape", "district": "Wedding", "theme": "Horror",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://roomescapeberlin.de/escape-spiel-buchen-berlin-wedding/",
     "room_url": "https://roomescapeberlin.de",
     "address": "Schulstraße 10, 13347 Berlin", "active": True},
    {"name": "Russenmafia", "provider": "your time2escape", "district": "Wedding", "theme": "Krimi",
     "players": "2-6", "duration": 60, "difficulty": "", "price_from": None,
     "booking_url": "https://roomescapeberlin.de/escape-spiel-buchen-berlin-wedding/",
     "room_url": "https://roomescapeberlin.de",
     "address": "Schulstraße 10, 13347 Berlin", "active": True},
]
